table 'Dim Geography'
	lineageTag: 8d54f2aa-da24-4d82-b8bc-500bb847f313

	column GeographyCode
		dataType: string
		isHidden
		isKey
		lineageTag: 8da0f83f-49c3-4d17-bbfb-3d9d3adb167b
		summarizeBy: none
		sourceColumn: GeographyCode

	column GeographyName
		dataType: string
		lineageTag: 92008839-8658-4afe-8899-3f68e0937cd4
		summarizeBy: none
		sourceColumn: GeographyName

	column GeographyLevel
		dataType: string
		lineageTag: 61550d06-0359-4354-b316-9453b7b31258
		summarizeBy: none
		sourceColumn: GeographyLevel
		sortByColumn: GeographyLevelSort

	column ParentGeographyCode
		dataType: string
		isHidden
		lineageTag: ff2cfdba-bba0-46eb-847f-9da6c0f690cc
		summarizeBy: none
		sourceColumn: ParentGeographyCode

	column ParentGeographyName
		dataType: string
		lineageTag: dab9729d-a18e-470c-9299-2d74bd604943
		summarizeBy: none
		sourceColumn: ParentGeographyName

	column CountryCode
		dataType: string
		isHidden
		lineageTag: 25cdf2ad-8872-46d1-8384-c6f32aeb67b8
		summarizeBy: none
		sourceColumn: CountryCode

	column CountryName
		dataType: string
		lineageTag: c6ca67dd-f91a-4c53-832f-997937e7c42c
		summarizeBy: none
		sourceColumn: CountryName

	column GeographyLevelSort
		dataType: int64
		isHidden
		lineageTag: ab90a562-aadd-4a99-bb29-0c75a8ef03ee
		summarizeBy: none
		sourceColumn: GeographyLevelSort

	column MapCountry
		dataType: string
		isHidden
		lineageTag: f98aa9fb-4335-4e1a-a5f6-9659df062297
		summarizeBy: none
		sourceColumn: MapCountry

	column GeoLabel
		dataType: string
		lineageTag: 62e972b6-242b-45d7-ac61-9414439fb964
		summarizeBy: none
		sourceColumn: GeoLabel

	column IsEngland
		dataType: boolean
		isHidden
		lineageTag: 176e7c2f-1e96-4a0d-a69b-b3cff1c141f0
		summarizeBy: none
		sourceColumn: IsEngland

	column IsWales
		dataType: boolean
		isHidden
		lineageTag: 3c56221e-52c4-4757-8d51-084fb1cd3d1b
		summarizeBy: none
		sourceColumn: IsWales

	column IsScotland
		dataType: boolean
		isHidden
		lineageTag: 4a1e4097-2d46-4f01-b88a-696955b1f7d9
		summarizeBy: none
		sourceColumn: IsScotland

	column IsNorthernIreland
		dataType: boolean
		isHidden
		lineageTag: b6c0b97b-be8a-45af-a89c-286df09f36ce
		summarizeBy: none
		sourceColumn: IsNorthernIreland

	partition 'Dim Geography' = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents(CuratedDataFolder & "\dim_geography.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
					Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					Typed = Table.TransformColumnTypes(Headers, {
						{"GeographyCode", type text},
						{"GeographyName", type text},
						{"GeographyLevel", type text},
						{"ParentGeographyCode", type text},
						{"ParentGeographyName", type text},
						{"CountryCode", type text},
						{"CountryName", type text},
						{"GeographyLevelSort", Int64.Type},
						{"MapCountry", type text},
						{"GeoLabel", type text},
						{"IsEngland", type logical},
						{"IsWales", type logical},
						{"IsScotland", type logical},
						{"IsNorthernIreland", type logical}
					}, "en-GB")
				in
					Typed

